{
  "swagger": "2.0",
  "info": {
    "title": "mytest",
    "version": "",
    "description": "mytest"
  },
  "paths": {
    "/myEndpoint": {
      "get": {
        "tags": [
          "MyDto"
        ],
        "summary": "Поиск",
        "operationId": "myOperationId1",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*"
        ],
        "deprecated": false,
        "x-security": {
          "check-permission": {
            "object": "myObject",
            "permission": "create"
          }
        },
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/MyDto"
              }
            }
          }
        }
      }
    },
      "v1/sms-verification/{processGUID}/{code}": {
        "get": {
          "tags": [
            "MyDto"
          ],
          "summary": "/sms-verification",
          "operationId": "dsSmsVerificationGETnonews_v1_0_SmsVerification",

          "consumes": [
            "application/json"
          ],
          "produces": [
            "*/*"
          ],
          "deprecated": false,
          "x-security": {
            "check-permission": {
              "object": "myObject",
              "permission": "create"
            }
          },
          "parameters": [
            {
              "name": "processGUID",
              "description": "processGUID",
              "required": true,
              "in": "path",
              "type": "string"
            },
            {
              "name": "code",
              "description": "code",
              "required": true,
              "in": "path",
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/ResultResponseFordsSmsVerificationGET"
                }
              }
            }
          }
        }
      },
    "/sms-verification/{phoneNumber}": {
      "post": {
        "tags": [
          "MyDto"
        ],
        "summary": "/sms-verification",
        "operationId": "dsSmsVerificationPOSTnonews_v1_0_SmsVerification",

        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*"
        ],
        "deprecated": false,
        "x-security": {
          "check-permission": {
            "object": "myObject",
            "permission": "create"
          }
        },
        "parameters": [
          {
            "name": "phoneNumber",
            "description": "phoneNumber",
            "required": true,
            "in": "path",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ResultResponseFordsSmsVerificationGET"
              }
            }
          }
        }
      }
    }

  },
  "definitions": {
    "ResultResponseFordsSmsVerificationGETnonews_v10_SmsVerification": {
      "type": "object",
      "title": "MyTitle",
      "properties": {
        "guid": {
          "description": "guid",
          "type": "string"
        },
        "secretCode": {
          "description": "secretCode",
          "type": "string"
        },
        "phoneNumber": {
          "description": "phoneNumber",
          "type": "string"
        }
      }
    },
    "ResultResponseFordsSmsVerificationPOSTnonews_v10_SmsVerification": {
      "type": "object",
      "title": "MyTitle2",
      "properties": {
        "guid": {
          "description": "guid",
          "type": "string"
        }
      }
    }

  }
}
